settings:
  store-open: true
  prefix: "&7&l[#c48ab8&lB#d9a3cb&lu#e7b3d8&ln#e7b3d8&ln#e78fc3&li#e759a3&le#e78fc3&lC#e7c5e3&lo#e7b3d8&li#e7b3d8&ln#c48ab8&ls&7&l]"
  currency-name: "BunnieCoins"
  database:
    type: SQLite #MongoDB, SQLite and MySQL are currently supported!
    mysql: #You only need to fill this if you set your type to MySQL.
      address: 127.0.0.1
      port: 3306
      username: Username
      password: Password
      database: bunniecoins
    mongo: #You only need to fill this if you set your type to MongoDB.
      address: 127.0.0.1
      port: 27017
      auth:
        enabled: false
        username: Username
        password: Password
        database: admin #Database where the user is located

messages:
  on-store:
    status:
      open: "%prefix% #C78DD3Store has now been #CCE5EAopened#C78DD3!"
      close: "%prefix% #C78DD3Store has now been #CCE5EAclosed#C78DD3!"
    fail:
      player-open: "&cStore is currently closed!"
      open: "&cStore is already opened!"
      close: "&cStore is already closed!"
  on-purchase:
    success: "%prefix% #C78DD3You have purchased&r %product.display-name%#C78DD3! &7(#CCE5EA%player.old-balance% -> %player.balance%&7)"
  on-refund:
    success: "%prefix% #C78DD3Refund has been issued for #CCE5EA%player%#C78DD3!"
  on-coins:
    balance: "%prefix% #C78DD3You have #CCE5EA%player.coins% %currency%#C78DD3!"
    receive:
      target: "%prefix% #C78DD3You have received #CCE5EA%coins% %currency%#C78DD3!"
      sender: "%prefix% #C78DD3You have added #CCE5EA%coins% %currency% to #CCE5EA%player%s' #C78DD3balance!"
    removal:
      target: "%prefix% #CCE5EA%coins% %currency% #C78DD3have been removed from your balance!"
      sender: "%prefix% #C78DD3You have removed #CCE5EA%coins% %currency% from #CCE5EA%player%s' #C78DD3balance!"
  on-history:
    load: "%prefix% #C78DD3Loading player #CCE5EA%player%s' #C78DD3purchase history!"