settings:
  store-open: true
  prefix: "&7&l[#c48ab8&lB#d9a3cb&lu#e7b3d8&ln#e7b3d8&ln#e78fc3&li#e759a3&le#e78fc3&lC#e7c5e3&lo#e7b3d8&li#e7b3d8&ln#c48ab8&ls&7&l]"
  currency-name: "BunnieCoins"
  database:
    type: SQLite #MongoDB, SQLite and MySQL are currently supported!
    mysql: #You only need to fill this if you set your type to MySQL.
      address: 127.0.0.1
      port: 3306
      username: Username
      password: Password
      database: bunniecoins
    mongo: #You only need to fill this if you set your type to MongoDB.
      address: 127.0.0.1
      port: 27017
      auth:
        enabled: false
        username: Username
        password: Password
        database: admin #Database where the user is located
  withdraw-note:
    name: "#C78DD3%currency% Note"
    lore:
      - "#C78DD3Withdrawn By: &f%player%"
      - "#C78DD3Withdraw Date: &f%withdraw.date%"
      - ""
      - "#C78DD3Right-Click this note to add #CCE5EA%coins% %currency% #C78DD3to your balance!"
    material: PAPER
    enchanted: true
messages:
  on-store:
    status:
      open: "%prefix% #C78DD3Store has now been #CCE5EAopened#C78DD3!"
      close: "%prefix% #C78DD3Store has now been #CCE5EAclosed#C78DD3!"
    fail:
      player-open: "&cStore is currently closed!"
      open: "&cStore is already opened!"
      close: "&cStore is already closed!"
  on-purchase:
    success: "%prefix% #C78DD3You have purchased&r %product.display-name%#C78DD3! &7(#CCE5EA%player.old-balance% -> %player.balance%&7)"
  on-refund:
    success: "%prefix% #C78DD3Refund has been issued for #CCE5EA%player%#C78DD3!"
  on-coins:
    balance:
     self: "%prefix% #C78DD3You have #CCE5EA%player.coins% %currency%#C78DD3!"
     other: "%prefix% ##CCE5EA%player% #C78DD3has #CCE5EA%player.coins% %currency%#C78DD3!"
    receive:
      target: "%prefix% #C78DD3You have received #CCE5EA%coins% %currency%#C78DD3!"
      sender: "%prefix% #C78DD3You have added #CCE5EA%coins% %currency% to #CCE5EA%player%s' #C78DD3balance!"
    removal:
      target: "%prefix% #CCE5EA%coins% %currency% #C78DD3have been removed from your balance!"
      sender: "%prefix% #C78DD3You have removed #CCE5EA%coins% %currency% from #CCE5EA%player%s' #C78DD3balance!"
    pay:
      target: "%prefix% #C78DD3You have received #CCE5EA%coins% %currency%#C78DD3 from #CCE5EA%sender%#C78DD3!"
      sender: "%prefix% #C78DD3You have sent #CCE5EA%coins% %currency% #C78DD3to #CCE5EA%target%#C78DD3!"
      self: "%prefix% #C78DD3You cannot pay #CCE5EA%currency% #C78DD3to yourself!"
  on-history:
    load: "%prefix% #C78DD3Loading player #CCE5EA%player%s' #C78DD3%history.type% history!"
  on-redeem:
    invalid: "%prefix% #C78DD3This #CCE5EA%currency% #C78DD3note is invalid!"
    not-found: "%prefix% #C78DD3Could not find #CCE5EA%currency% #C78DD3note within the database!"
    already-redeemed: "%prefix% #C78DD3This #CCE5EA%currency% #C78DD3note has already been redeemed!"
    notify: "%prefix% #C78DD3Player #CCE5EA%player% #C78DD3may have a duplicated #CCE5EA%currency% #C78DD3note! Redeem attempt was cancelled."
    success: "%prefix% #C78DD3Redeemed #CCE5EA%currency% #C78DD3note! #CCE5EA%coins% #C78DD3added to your balance! &7(#CCE5EA%player.old-balance% &7-> #CCE5EA%player.new-balance%&7)"
  on-withdraw:
    invalid: "%prefix% #C78DD3Unable to process this withdrawal! You only have #CCE5EA%coins% %currency% #C78DD3!"
    success: "%prefix% #C78DD3You have withdrawn #CCE5EA%coins% %currency%#C78DD3!"
placeholders:
  history-types:
    purchase: "purchase"
    withdraw: "withdraw"
    deposit: "deposit"
  purchase-history:
    refund-status:
      true: "&aRefunded"
      false: "&8&mRefunded"
  withdraw-history:
    withdrawn-status:
      true: "&aWithdrawn"
      false: "&8&mWithdrawn"