name: BunnieCoins
version: '${project.version}'
main: me.bunnie.bunniecoins.BCPlugin
description: Adds a premium currency to your server
author: xbunnies
api-version: '1.13'
softdepend: [PlaceholderAPI]
libraries:
  - org.mongodb:mongo-java-driver:3.12.11