products:
  seraph:
    name: "Seraph"
    category: "rank"
    lore:
      - ""
    material: EMERALD
    slot: 0
    price: 1500
    purchase-commands:
      - "say %player% has purchased Seraph rank!"
    refund-commands:
      - "say %player% has refunded their Seraph rank!"
